M07 assessment
ctobler40/dev10-classwork pull request #10
Opened 2023-09-25 14:09 UTC by ctobler40

2023-09-25 15:17 UTC, esin87 requested changes
Overall very nice work, CJ. Code is easy to read and follow. Most of the functionality is there. Nice work making progress on the UI improvements and showing agencies and aliases. Here are the changes I'd like you to make: 

- [ ] Show form validation errors on POST and PUT. Leverage existing code and patterns. 

Grade: Not Yet

2023-09-25 15:17 UTC, esin87 commented on week-07/lessons/Promises + Async/Async.js
> +}
Next time remember to add and commit your work on main before checking out your assessment branch, it's easier to focus on your assessment code if we don't have a ton of other files on the PR

2023-09-25 15:17 UTC, esin87 commented on week-07/assessment/field-agent-ui/js/index.js
> +    changeView("del");
Nice!

2023-09-25 15:17 UTC, esin87 commented on week-07/assessment/field-agent-ui/js/index.js
> +                    renderErrors(errors.messages);
The field agent API returns an array of messages on 400 errors. We're not seeing these populate. What do we need to change here to see the validation errors? Hint: Look at how it was working before for post.

2023-09-25 15:17 UTC, esin87 commented on week-07/assessment/field-agent-ui/js/index.js
> +                    renderErrors(errors.messages);
You don't seem to have a function called `renderErrors` ... the previous code already has a method you can use to show validation issues.

2023-09-25 15:17 UTC, esin87 commented on week-07/assessment/field-agent-ui/js/index.js
> +    });
Nice working showing agencies! However, the onclick handlers need to be updated, maybe `showAgencyDelete`, so that they don't call the agent-related functions.

2023-09-27 17:00 UTC, ctobler40 commented
no more assessments

2023-09-27 17:00 UTC, merged